version: '2'
services:
  config-service:
    image: herasimau/config-service
    restart: always
    environment:
    - CONFIGURATION_REPOSITORY=https://github.com/herasimau/tips-config.git
    - CONFIGURATION_BRANCH=master
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 8888:8888

  eureka-service:
    image: herasimau/eureka-service
    restart: always
    depends_on:
    - config-service
    links:
    - config-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    ports:
          - 8761:8761
  auth-service:
    image: herasimau/auth-service
    restart: always
    depends_on:
    - config-service
    - eureka-service
    links:
    - config-service
    - eureka-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 9191:9191

  api-service:
    image: herasimau/api-service
    restart: always
    depends_on:
    - config-service
    - eureka-service
    links:
    - config-service
    - eureka-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 8000:8000

  api-client:
    image: herasimau/api-client
    restart: always
    depends_on:
    - config-service
    - eureka-service
    links:
    - config-service
    - eureka-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 8100:8100

  hystrix-dashboard:
    image: herasimau/hystrix-dashboard
    restart: always
    depends_on:
    - config-service
    - eureka-service
    links:
    - config-service
    - eureka-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 8010:8010

  registration-service:
    image: herasimau/registration-service
    restart: always
    depends_on:
    - config-service
    - eureka-service
    links:
    - config-service
    - eureka-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 9292:9292

  zipkin-service:
    image: herasimau/zipkin-service
    restart: always
    depends_on:
    - config-service
    - eureka-service
    links:
    - config-service
    - eureka-service
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - 9411:9411